Wom 23
iDenisOff/womba pull request #13
Opened 2023-06-08 11:16 UTC by Wononi

### Какую задачу решаем
Страница завершения игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-08 17:18 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Несмотря на то что большинство комментов не критичные, всё ж прощу их учесть и сделать. Принимая во внимания, что твоя задача имеет низкий весь, будет полезно тебе ознакомится с рекомендациями и улучшить проект.
Основные замечания которые следует в приоритете поправить:
- Доработать Button компонент так, чтобы не приходилось в местах его использования добавлять лишние стилы. Кастомизацию необходимо настроить через props-ы. В качестве примера можешь посмотреть https://mui.com/material-ui/react-button/ (не реализацию, а итог)
- Перенести в токены как минимум цвета.

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/EndScreen/inedx.tsx
> +  return <>
Нет смысла их добавить если у тебя только один child

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/StartScreen/index.tsx
> +        <Button className={'start__btn'}>Начать играть</Button>
Через скобки передают обычно переменную, строку проще передать напрямую
 ```suggestion
        <Button className="start__btn">Начать играть</Button>
```

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/end.tsx
> +  )
```suggestion
  return <EndScreen />
```

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/start/start.tsx
> +  )
```suggestion
  return <StartScreen />
```

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/EndScreen/inedx.tsx
Опечатка в имени файла `inedx` -> `index`

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/Router/routes.ts
> +  End = '/end',
Советую добавить ещё один роут для Home
```suggestion
  End = '/end',
  Home = '/,
```

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/EndScreen/inedx.tsx
> +      <NavLink className='end__btn' to={'/'}>На главную</NavLink>
```suggestion
      <NavLink className='end__btn' to={Routes.Home}>На главную</NavLink>
```

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/EndScreen/inedx.tsx
> +      <NavLink className='end__btn' to={'/'}>На главную</NavLink>
Рекомендую ознакомиться с БЭМ-ом (ещё раз, если уже смотрел). [Необязательность](https://ru.bem.info/methodology/quick-start/#%D0%BD%D0%B5%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C).

Кнопки не обязательно элемент блока. Поэтому ты можешь называть их просто называть `button`, или c добавлением [модификатора](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80) link: `button_link`.

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/containers/EndScreen/inedx.tsx
> +      <NavLink className='end__btn' to={'/'}>На главную</NavLink>
Почему лучше просто button? Потому что у вас в идеале должен быть один источник правды для кнопок, с разными модификаторами разумеется. Таким образом вас удаётся легко управлять всеми кнопками в проекте.

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/end.tsx
Подскажи, пожалуйста, какая у вас цель разделить компоненты на containers и pages?

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/styles.scss
> +  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.75);
Лучше перенести это в токены (переменные). [Пример](https://paradigm.mail.ru/design_tokens/borders_shadows).

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/styles.scss
> +    line-height: 110%;
Типографику в идеале тоже лучше перенести в токены и сделать отдельные компоненты под h2, h3, и т.д.
https://paradigm.mail.ru/design_tokens/typography

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/styles.scss
> +    line-height: 110%;
Посмотри например https://mui.com/material-ui/react-typography/, у них один компонент для текстов с помощью которого можно нарисовать разные текста. Но самое главное что у вас во всём проекте будет одни и те ж размеры h2, h3, h1 и т.д. У вас будет меньше дублирование кода и единая точка компонентов.

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/start/styles.scss
> +          color: #fff;
Все цвета тоже надо перенести в токены (переменные). [Пример](https://paradigm.mail.ru/design_tokens/colors).

2023-06-08 17:18 UTC, bin-umar commented on packages/client/src/pages/end/styles.scss
> +  }
Эти стилы должны быть в самом компоненте Button, тут максимум, что должен быть это какие-то второстепенные стили из разряда margin, в целом позиционирование.

2023-06-08 17:19 UTC, bin-umar commented on packages/client/src/pages/start/styles.scss
> +    line-height: 110%;
Не уверен, что 110% всегда идеальное значение. Мне кажется если перенести их в токены, то лучше будет указать конкретную цифру.

2023-06-10 23:41 UTC, bin-umar commented
@Wononi привет! Собираешься ли ты исправить замечания, или просто руки не дошли?)

2023-06-15 09:45 UTC, Wononi commented
Конечно собираюсь исправить

2023-06-19 11:41 UTC, bin-umar commented on packages/client/src/ui/components/Typography/Typography.tsx
> +  component: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
Чем отличается компонент от вариант, и почему бы их не объеднить?

2023-06-19 11:42 UTC, bin-umar commented on packages/client/src/ui/components/Typography/Typography.tsx
> +  component: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
Ведь если их не объединит, то у тебя можно создать component=p и variant=h1. Мне кажется это невалидный кейс.

2023-06-19 11:43 UTC, bin-umar commented on packages/client/src/pages/start/styles.scss
> +          color: #fff;
Цвета всё ещё не в токены выведены.

2023-06-27 11:06 UTC, closed without merging