Wom 19
iDenisOff/womba pull request #14
Opened 2023-06-09 21:13 UTC by alexandrkaa

Добвлен контейнер и страница LEaderBoard с базовой версткой

2023-06-11 09:39 UTC, ManukMamyan requested changes

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Profile/profile.tsx
> +// import { useForm } from 'react-hook-form'
удали, если этот модуль не нужен

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Leaderboard/styles.scss
> +  padding: 5px;
вынеси в переменную

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Leaderboard/Leaderboard.tsx
> +const LeaderBoard: React.FC<TLeaderBoardProps> = props => {
переименуй файл в каммел кейс

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Profile/profile.tsx
> +const onSubmit = (data: any) => {
старайся избегать any

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Profile/profile.tsx
> +    if (evt && evt.target && evt.target.files) {
зачем проверять на наличие evt и evt,target? Разве они могут быть undefined?

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Profile/profile.tsx
> +      {mode !== EditModes.EDIT && (
создай функции 

```js
const hasEditMode = () => {
 return mode === EditModes.EDIT
}
```
и для остальных проверок, Нужно убрать дублирование

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/src/containers/Profile/profile.tsx
> +// export default ProfileForm
лучше убрать все закомментированное

2023-06-11 09:39 UTC, ManukMamyan commented on packages/client/package.json
> +    "path": "^0.12.7",
зачем нужна эта зависимость?

2023-06-11 18:40 UTC, iDenisOff reviewed
Файлы .DS_Store, packages/.DS_Store не нужно добавлять в пр, получил в прошлый раз такой комментарий от ревьюера

2023-06-11 18:40 UTC, iDenisOff commented on packages/client/package.json
> +    "classnames": "^2.3.2",
Давай жестко фиксировать версии пакетов. Для нашего проекта не принципиально, но привычка полезная

2023-06-11 18:40 UTC, iDenisOff commented on packages/client/src/containers/Profile/profile.tsx
> +import { useState } from 'react'
В задаче страница лидерборда, а код со страницей профиля)

2023-06-11 18:40 UTC, iDenisOff commented on packages/client/src/containers/Profile/profile.tsx
> +      <button onClick={switchEditMode} className="link">
Почему не использовал готовый компонент <Button>?

2023-06-11 18:40 UTC, iDenisOff commented on packages/client/src/containers/Profile/profile.tsx
> +        <FormControl className="form-control form-control--profile">
Пять одинаковых блоков <FormControl>, стоит вынести в отдельный компонент

2023-06-17 10:22 UTC, ManukMamyan approved these changes

2023-06-17 17:01 UTC, merged