WOM-26
iDenisOff/womba pull request #15
Opened 2023-06-12 16:56 UTC by ManukMamyan

### Какую задачу решаем
Реализовать одну из игровых механик

- реализовано управление игрой стрелками(право, лево, верх, вниз) и клавишами (wsad)
- после хода квадраты с одинаковыми значениями сливаются в направлении сделанного хода
- квадраты с разным номиналом окрашиваются в разные цвета
- реализован подсчет текущего счета и сохранение лучшего (без localstorage)
- при нажатии кнопки New Game сбрасывается счет и восстанавливается начальное положение для новой игры
- реализована логика проверки окончания игры(если невозможно сделать ход) 

### Скриншоты/видяшка (если есть)
![ПФЬУ!!!!!!!!!!!](https://github.com/iDenisOff/womba/assets/44231001/8ca0bfff-5f03-4fe7-9d53-c9baaca13f17)

### TBD (если есть)

2023-06-13 16:51 UTC, sibstark commented on packages/client/src/pages/Game/components/Header/index.tsx
> +        <button className="header__new_button" onClick={startNewGame}>
может стоит использовать кнопку из компонентов? <Button />

2023-06-13 17:31 UTC, sibstark approved these changes

2023-06-15 21:05 UTC, Olegas requested changes

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/containers/GameContainer/index.tsx
>  type TCanvasProps = {
Этот тип ранее видимо описывал только сам canvas, а теперь тут появились дополнительные свойства и это уже TGameProps

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/board/BoardCanvas.ts
>      this.#boardArray.setRandomValue()
Для чего одна и та же операция тут выполняется дважды?

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/board/BoardCanvas.ts
>          const squareBoxHeight = this.#SQUARE_HEIGHT - this.#SQUARE_GAP
Вот эти две константы не зависят ни от colIdx ни от rowIdx - их можно вынести вверх функции drawSquares.
А topLeftY не зависит от colIdx - можно вынести в предыдущий колбэк (board.forEach)

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/board/BoardCanvas.ts
> +        switch (val) {
Тут получилась копипаста. По сути кейсы ничем не отличаются, только цветом. Надо сделать объект с соответствием число-цвет и использовать его, тогда switch/case не понадобится и код сократится в разы

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/game/Game.ts
> +  updateScore(callback: (score: number) => void) {
Для чего тут используется колбэк? Функция явно синхронная. Почему просто не вернуть из нее текущее значение score?

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/game/Game.ts
> +  checkEndConditions(callback: (isGameOver: boolean) => void) {
Аналогичный вопрос тут - почему просто не вернуть true/false из функции? Зачем делать колбэк?

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/board/BoardArray.ts
> +            currentCell.isAvailable = !currentCell.val
currentCell.val тут всегда = 0, а значит !currentCell.val всегда будет true

2023-06-15 21:05 UTC, Olegas commented on packages/client/src/core/board/BoardArray.ts
> +  moveDown() {
Все функции move* очень похожи друг на друга. Аналогично все merge* похожи друг на друга. Подумай, нельзя ли избавиться от копипасты, сделать например универсальную функцию move() и передавать в нее направление (например move(0, 1), move(-1, 0) и т.п.)

2023-06-17 10:35 UTC, ManukMamyan commented on packages/client/src/containers/GameContainer/index.tsx
>  type TCanvasProps = {
переименовал

2023-06-17 10:36 UTC, ManukMamyan commented on packages/client/src/core/board/BoardCanvas.ts
>      this.#boardArray.setRandomValue()
При инициализации игры нам нужно заполнить 2 значения. Далее по одному значению после каждого хода

2023-06-17 10:47 UTC, ManukMamyan commented on packages/client/src/core/board/BoardCanvas.ts
>          const squareBoxHeight = this.#SQUARE_HEIGHT - this.#SQUARE_GAP
вынес в константы

2023-06-17 11:20 UTC, ManukMamyan commented on packages/client/src/core/board/BoardCanvas.ts
> +        switch (val) {
отрефакторил

2023-06-17 11:43 UTC, ManukMamyan commented on packages/client/src/core/game/Game.ts
> +  updateScore(callback: (score: number) => void) {
отрефакторил

2023-06-17 11:43 UTC, ManukMamyan commented on packages/client/src/core/game/Game.ts
> +  checkEndConditions(callback: (isGameOver: boolean) => void) {
отрефакторил

2023-06-17 11:47 UTC, ManukMamyan commented on packages/client/src/core/board/BoardArray.ts
> +            currentCell.isAvailable = !currentCell.val
отрефакторил

2023-06-17 12:19 UTC, ManukMamyan commented on packages/client/src/core/board/BoardArray.ts
> +  moveDown() {
Не думаю, что это хорошая идея - визуально функции кажутся похожими, но в реальности есть серьезные отличия.  В одной мы проходим по массиву с лева на право, в другой с права на лево, отступы от границы доски тоже разные. И таких нюансов много. Попытка обьеденить все это приведет к еще большему кол-ву if() {} и запутает код еще больше. Здесь я предпочту небольшое дублирование

2023-06-17 16:31 UTC, Olegas approved these changes
Спасибо, все ок.

2023-06-17 16:31 UTC, Olegas commented on packages/client/src/core/board/BoardArray.ts
> +  moveDown() {
Ок, согласен.

2023-06-18 10:12 UTC, merged