Подключение redux
iDenisOff/womba pull request #19
Opened 2023-06-18 07:55 UTC by iDenisOff

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-18 08:53 UTC, Olegas requested changes
1. Есть замечания по коду
2. Выглядит недоделанным. Вы храните в redux логин и пароль пользователя, селектор при этом написан только для логина. Но и эти данные нигде не используются.

2023-06-18 08:53 UTC, Olegas commented on packages/client/src/main.tsx
> +      <Root />
Тут видимо опечатка. Два раза компонент Root вставлен.

2023-06-18 08:53 UTC, Olegas commented on packages/client/src/containers/login/index.tsx
> +        }}
Тут бы применить useMemo для значения options и useCallback для значения onChange. Иначе каждый рендер эти свойства будут новые и будут вызывать перерисовку компонента  FormControlInputTemplate

2023-06-18 08:53 UTC, Olegas commented on packages/client/src/types/state.ts
> +}
Этот тип не надо описывать руками, его можно выводить автоматически. Посмотрите вот тут: https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

2023-06-18 08:53 UTC, Olegas commented on packages/client/src/pages/login/index.ts
> +export { reducer } from './redux/reducer'
Несколько необычное расположение. Обычно визуальные компоненты отделяют от состояния. Не более чем рекомендация к обсуждению.

2023-06-18 09:17 UTC, iDenisOff commented on packages/client/src/main.tsx
> +      <Root />
Да, сверху лишний, убрал

2023-06-18 09:29 UTC, iDenisOff commented on packages/client/src/types/state.ts
> +}
Исправил

2023-06-18 10:00 UTC, iDenisOff commented on packages/client/src/containers/login/index.tsx
> +        }}
Добавил

2023-06-18 10:04 UTC, iDenisOff commented
> * Есть замечания по коду
> * Выглядит недоделанным. Вы храните в redux логин и пароль пользователя, селектор при этом написан только для логина. Но и эти данные нигде не используются.

По заданию подключил redux, добавил слайс для пользователя и положил туда логин

2023-06-18 15:41 UTC, Olegas commented
> По заданию подключил redux, добавил слайс для пользователя и положил туда логин

@iDenisOff в задаче нужно было складывать не логин, а данные пользователя после логина в приложение. Вот как я вижу эту задачу в бэклоге:
1. Добавить в проект redux-toolkit. - это сделано
2. Добавить слайс для юзера (к примеру). - это сделано
3. После авторизации класть информацию о юзере в слайс. - это не сделано. 

Надо после авторизации данные о пользователе сложить в redux и везде в приложении брать их оттуда.
В текущем виде задачу принять не могу. Давайте доделывать.

2023-06-22 05:39 UTC, Olegas requested changes
Стало лучше, но есть ошибки. Указал на них в комментариях к коду + дал рекомендации как правильно организовать работу с сетью

2023-06-22 05:39 UTC, Olegas commented on packages/client/src/containers/login/index.tsx
> +          const dispatch = useDispatch()
Так нельзя делать
1. Нарушено правило что хук используется либо из компонента либо из другого хука - здесь он используется из функции
2. Нарушено правило что хуки должны вызываться всегда в одном составе и в одном порядке - здесь порядок зависит от внешних обстоятельств
Подключите правило ESLint для своевременного обнаружения.
Подробнее в документации: https://legacy.reactjs.org/docs/hooks-rules.html

Работу с сетью лучше переместить в async thunk - там будет доступ к dispatch
https://redux-toolkit.js.org/api/createAsyncThunk

2023-06-23 17:37 UTC, Olegas approved these changes
Принимаю. На будущее обратите внимание на то, что запрос может не выполниться или упасть с ошибкой. В этом случае надо выставить какой-то флаг или зачистить слайс - но это уже зависит от логики приложения что именно и как сделать

2023-06-24 09:10 UTC, merged