Добавляет тесты для движка игры и компонента button
iDenisOff/womba pull request #20
Opened 2023-06-22 12:37 UTC by Wononi

### Какую задачу решаем
Добавляет тесты для движка игры и компонента button
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-22 13:21 UTC, IvanPeleshok approved these changes

2023-06-22 13:22 UTC, IvanPeleshok commented
Конечно, хотелось бы видеть побольше тестов, но цель минимально покрыта функционалом :)

2023-06-22 17:21 UTC, ManukMamyan requested changes

2023-06-22 17:21 UTC, ManukMamyan commented on packages/client/src/__tests__/game.test.tsx
> +    board.moveDown()
без шага тоже должно работать

2023-07-23 12:34 UTC, ManukMamyan approved these changes

2023-07-26 08:26 UTC, merged