WOM-34, WOM-35
iDenisOff/womba pull request #25
Opened 2023-07-06 14:53 UTC by sibstark

- Cерверный рендеринг статических React-страниц
- Настройка Node Express 
- Настройка Vite для SSR
- Настройка React для SSR
- Настройка SSR роутинга
- Redux заполняется из предзагруженных данных с сервера window.__REDUX_STATE__
- Настройка команд для билда, запуска в дев режиме сервера

2023-07-08 10:26 UTC, ManukMamyan approved these changes

2023-07-08 14:08 UTC, Olegas requested changes
Прошу переделать. Давайте не будем смешивать изменения стилей написания кода и задач, которые сдаются на проверку. Разделите пожалуйста на несколько PR. Если вам нужно отрефакторить, поменять кавычки, отступы - сделайте это отдельным PR. На ревью прошу отдать PR где изменения только по теме задачи.

2023-07-12 06:24 UTC, Olegas commented on packages/server/user.ts
> +        return await response.json();
Совет: return await - в этой конструкции нет смысла. Можно просто вернуть response.json()

2023-07-12 06:26 UTC, Olegas commented on packages/client/src/redux/store.ts
> +    if (store) {
Из-за этой конструкции у вас store стал глобальным на все приложение. Каждый клиент, который запросит страницу, получит store от предыдущего запроса. Не надо так делать. Стор у каждого клиента, у каждого запроса, должен быть свой.
Это нужно переделать.

2023-07-12 06:27 UTC, Olegas requested changes
Есть одно критическое замечание и один совет. Критическое замечание - надо исправить.

2023-07-12 06:32 UTC, sibstark commented on packages/client/src/redux/store.ts
> +    if (store) {
Добрый день. Не очень понял где именно проблема, можете более подробно описать ? 
`    if (store) {
        return store;
    }` как я понял проблема в этом? нужно в любом случае пересоздавать стор?

2023-07-12 12:25 UTC, sibstark commented
@Olegas Добрый день, я все поправил из замечаний.

2023-07-12 18:40 UTC, Olegas approved these changes

2023-07-13 17:41 UTC, merged