Wom 37
iDenisOff/womba pull request #27
Opened 2023-07-11 07:59 UTC by iDenisOff

Добавить API для лидерборда

2023-07-11 09:35 UTC, ManukMamyan approved these changes

2023-07-11 14:36 UTC, IvanPeleshok commented on packages/client/src/redux/leaders/slice.ts
> +    const api = new LeadersApi();
Предлагаю импортировать уже созданный экземпляр класса LeadersApi

2023-07-11 14:38 UTC, IvanPeleshok requested changes
Есть замечание по импорту класса

2023-07-12 13:29 UTC, IvanPeleshok approved these changes

2023-07-12 13:39 UTC, merged