Wom 36
iDenisOff/womba pull request #29
Opened 2023-07-11 17:33 UTC by alexandrkaa

### OAuth
Добавил OAuth авторизацию через yandex

2023-07-12 20:29 UTC, iDenisOff reviewed
Мелкое замечание

2023-07-12 20:29 UTC, iDenisOff commented on packages/client/src/api/oauth-api.ts
> +}
Давай сразу экспортировать экземпляр класса, чтобы каждый раз не создавать новый:

export default new OAuthAPI();

2023-07-13 10:59 UTC, alexandrkaa commented on packages/client/src/api/oauth-api.ts
> +}
Поправил

2023-07-13 11:24 UTC, iDenisOff approved these changes

2023-07-13 12:39 UTC, IvanPeleshok commented on packages/client/src/containers/Layout/index.tsx
> +    const OAuthId = useSelector(getOAuthId);
Константы с маленькой буквы

2023-07-13 12:39 UTC, IvanPeleshok commented on packages/client/src/containers/login/index.tsx
> +    const OAuthId = useSelector(getOAuthId);
Аналогично

2023-07-13 12:40 UTC, IvanPeleshok commented on packages/client/src/containers/login/index.tsx
>  const RenderLoginForm: React.FC<RenderLoginFormProps> = props => {
К PR не относится, но как рекомендация: необязательно приписывать Render к компоненту, называйте их как сущности: LoginForm / Button и т.д

2023-07-13 12:44 UTC, IvanPeleshok commented on packages/client/src/redux/user/slice.ts
> +        const api = new AuthAPI();
Предлагаю экспортировать уже созданный экземпляр AuthAPI, иначе придётся при каждом его использовании создавать новый
Импортируем и используем методы класса

2023-07-13 12:45 UTC, IvanPeleshok commented on packages/client/src/redux/user/slice.ts
> +        return await api.getUser();
В eslint есть правильно на эту тему: не рекомендуется использовать совместно return и await
Предлагаю разделить смысловые блоки на две строки:
```
const response = await request
return response
```

2023-07-13 12:46 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-13 19:40 UTC, IvanPeleshok approved these changes

2023-07-20 09:52 UTC, merged