Wom-20
iDenisOff/womba pull request #3
Opened 2023-06-02 16:54 UTC by iDenisOff

Страница игры

2023-06-02 17:09 UTC, sibstark reviewed
Все хорошо, есть 1 замечание и один вопрос на подумать команде)

2023-06-02 17:09 UTC, sibstark commented on packages/client/src/containers/Router/index.tsx
Нам бы договориться как именовать папки и файлы, а то я именую с строчной буквы и файлы и папки

2023-06-02 17:09 UTC, sibstark commented on packages/client/src/pages/Game/components/Header/index.tsx
> +          onClick={() => {
https://legacy.reactjs.org/docs/faq-functions.html
https://javascript.plainenglish.io/5-ways-to-optimize-your-functional-react-components-cb3cf6c7bd68#a5b8

```Using an arrow function in render creates a new function each time the component renders, which may break optimizations based on strict identity comparison.```
В официальной документации говорится что лучше не использовать стрелочные функции в render части
лучше их оборачивать в useCallback

2023-06-04 13:31 UTC, sibstark approved these changes

2023-06-05 18:42 UTC, ManukMamyan approved these changes

2023-06-05 22:34 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Много лишних файлов в ПР-е, удали их всех, пожалуйста. Также будет хорошо если сразу исправишь замечания по БЭМ-у. Про дизайн токены можешь ознакомиться и с командой поделиться, если решите сделать отдельной задачей, то ок, если сделаете в этот, то с удовольствием посмотрю.

2023-06-05 22:34 UTC, bin-umar commented on .DS_Store
Добавь, пожалуйста, этот файл (всех таких ж) в .gitignore, и удали его из истории гита.

2023-06-05 22:34 UTC, bin-umar commented on .yarn/releases/yarn-1.22.19.cjs
Это тоже лишний файл, его в репе быть не должно.

2023-06-05 22:34 UTC, bin-umar commented on .yarnrc.yml
Соответственно и этот :)

2023-06-05 22:34 UTC, bin-umar commented on packages/client/src/pages/Game/components/Footer/index.tsx
> +      <span className="footer_text">
Раз уж решили наименовать классы самостоятельно, давайте лучше используем [БЭМ](https://ru.bem.info/methodology/), тут правильнее будет:
```suggestion
      <span className="footer__text">
```
блок__элемент

2023-06-05 22:34 UTC, bin-umar commented on packages/client/src/pages/Game/components/Header/index.tsx
> +        <span className="header__block_title">
По БЭМ-у, block это элемент header-а, а title элемент2 block__elem1__elem2
```suggestion
      <div className="header__block">
        <span className="header__block__title">
```

2023-06-05 22:34 UTC, bin-umar commented on packages/client/src/pages/Game/components/Header/index.tsx
> +        <div className="header__block_content">
```suggestion
        <div className="header__block__content">
```

2023-06-05 22:34 UTC, bin-umar commented on packages/client/src/index.css
> +    background-color: #faf8ef;
Все цвета необходимо вывести в scss константы. 

Основной смысл этих переменных это выделение цветов в дизайн-токены. А смысл дизайн токенов в том чтобы в случае редизайна или изменения конкретного значения токена изменился бы в одном месте.
Но надо помнить что не стоит группировать по значению, так как это бессмысленно, а надо по css свойствам.

В качестве примера можешь посмотреть https://paradigm.mail.ru/design_tokens/colors, можешь на его примере убедиться что белый цвет например используется в трёх разных токенах.

Ну и в целом рекомендую прочитать про [дизайн-токенов](https://paradigm.mail.ru/design_tokens).

2023-06-05 22:34 UTC, bin-umar commented on packages/client/src/pages/Game/components/Header/styles.scss
> +      font-size: 20px;
Также лучше будет вывести font-size c привязкой line-height вывести в дизайн-токены https://paradigm.mail.ru/design_tokens/typography

2023-06-05 22:34 UTC, bin-umar commented on yarn-error.log
Удали пожалуйста этот файл тоже.

2023-06-05 22:34 UTC, bin-umar commented on yarn-error.log
Можно заодно сразу в .gitignore

2023-06-05 22:34 UTC, bin-umar commented on yarn.lock
> +  resolved "https://npm.yandex-team.ru/@types%2fcors/-/cors-2.8.12.tgz?rbtorrent=bd5aabc1a25da4d15590ced48d35c91d4ee7baf9#6b2c510a7ad7039e98e7b8d3d6598f4359e5c080"
Мне кажется npm.yandex-team.ru это приватная штука и попала сюда случайным образом, лучше вернуть registry.npmjs.org

2023-06-06 16:48 UTC, bin-umar commented
@iDenisOff Жду от тебя фиксов.

2023-06-07 14:25 UTC, iDenisOff commented on packages/client/src/index.css
> +    background-color: #faf8ef;
Сделаем организовано в следующем спринте

2023-06-07 14:25 UTC, iDenisOff commented on packages/client/src/pages/Game/components/Header/styles.scss
> +      font-size: 20px;
Сделаем организовано в следующем спринте

2023-06-07 14:32 UTC, iDenisOff commented
>

2023-06-07 16:28 UTC, bin-umar approved these changes

2023-06-08 11:26 UTC, merged