WOM-44
iDenisOff/womba pull request #39
Opened 2023-07-25 16:43 UTC by sibstark

Эмодзи (бэкенд)

1. Reaction - принимает строку (любое кодовое представление иконки, эмодзи) для отрисовки реакций.

2. Добавлены связи на модель Reaction для моделей 
- Post
- Comment
- Reply

Любая из сущностей может иметь реакцию, не только Reply

3. Модифицирован запрос на получение Post по id - вместе с постом возварщаются его Reaction, Comment Reaction, Reply Reaction

Добавлен вывод в консоль SQL запросов для дебага того какой запрос шлется в базу

2023-07-25 17:03 UTC, ManukMamyan requested changes

2023-07-25 17:03 UTC, ManukMamyan commented on packages/server/services/SequelizeClient.ts
> +connection.addHook("beforeFind", options => {
я так понимаю это для дебага было добавлено? Нужно удалить, если не используется

2023-07-25 17:03 UTC, ManukMamyan commented on packages/server/controllers/reactionController.ts
> +    const postId = request.query["postId"];
не совсем понял, как это работает, учитывая, что в рауте не предусмотрены квери параметры

2023-07-25 17:06 UTC, sibstark commented on packages/server/controllers/reactionController.ts
> +    const postId = request.query["postId"];
http://localhost:3001/api/reactions?postId=1&replyId=2 вот так

2023-07-25 17:10 UTC, ManukMamyan approved these changes

2023-07-25 18:54 UTC, Olegas commented on packages/server/controllers/reactionController.ts
> +    }
Совет: можно написать короче, за одну операцию так сказать, что бы не перебирать варианты (и потенциально ошибиться в переборе)
```
[postId, replyId, commentId].filter(i => !!i).length > 1
```

2023-07-25 18:56 UTC, Olegas commented on packages/server/controllers/reactionController.ts
> +    const postId = request.query["postId"];
Судя по коду ранее, в проекте принято применять деструктуризацию. Почему не 
```
const { replyId, commentId, postId } = request.query
```
?

2023-07-25 19:01 UTC, Olegas commented on packages/server/controllers/reactionController.ts
> +    }
Еще можно поменять на == 1 и тогда это сразу даст проверку что точно указана одна связь, не 0 и не 2 и не 3

2023-07-25 19:03 UTC, Olegas commented on packages/server/controllers/reactionController.ts
> +        const reactions = await Reaction.findAll({
А что за сценарий, когда нам надо одним запросом получить реакции сразу для нескольких сущностей? Я к тому что кажется тут не хватает проверки на то что у нас не попросили реакции сразу и к постам и к реплаям и к каментам.

2023-07-25 19:04 UTC, Olegas commented on packages/server/models/Reaction.ts
> +    comment?: Comment;
На поля commentId, replyId, postId нужны индексы. Добавление foreignKey не является добавлением индекса, это только лишь ограничение.

2023-07-25 19:04 UTC, Olegas requested changes
Добрый день.
Написал несколько замечаний к коду
Нужно доработать

2023-07-25 19:07 UTC, Olegas commented
Еще надо не забыть сделать каскадное удаление реакций при удалении постов, каментов, реплаев

2023-07-26 17:27 UTC, Olegas approved these changes
Работа принята

2023-07-26 18:06 UTC, merged