Wom 45
iDenisOff/womba pull request #40
Opened 2023-07-29 18:35 UTC by iDenisOff

Переключение тем (бак)

2023-07-30 14:07 UTC, ManukMamyan approved these changes

2023-07-30 17:50 UTC, Olegas requested changes
Добрый день.
Есть ошибка (неправильный уникальный индекс) и вопросы к коду (отключения правил eslint по непонятной причине).
Написал подробно в комментариях.
Нужно доработать

2023-07-30 17:50 UTC, Olegas commented on packages/server/models/Theme.ts
> +    @Unique
Тут вот ошибка. Сделан уникальный индекс на колонку theme, но тогда получиться что два разных пользователя не смогу поставить одну тему. И вообще, как только кто-то поставит, допустим, темную, никто больше не сможет.
Уникальный индекс должен быть на пару полей theme, userId

2023-07-30 17:50 UTC, Olegas commented on packages/server/models/User.ts
> +// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
Разве эти импорты не используются? Они ведь дальше используются в файле. Зачем тогда гасить eslint?  Относится ко всем отключениям правила unused-vars в этом файле и где-то еще в PR видел то же самое.

2023-07-30 19:13 UTC, iDenisOff commented on packages/server/models/User.ts
> +// eslint-disable-next-line no-unused-vars,@typescript-eslint/no-unused-vars
В данном месте убрал, действительно игнорирование здесь излишне. Но eslint продолжает ругаться на импорты из sequelize-typescript

2023-07-31 05:59 UTC, Olegas requested changes
Извиняюсь, в прошлом ревью я ошибся и дал некорректный комментарий. Уникальный индекс на пару userId-theme делать конечно же нельзя (ведь тогда один пользователь сможет сощдать сколь угодно много записей с разными темами). Но и убирать совсем - тоже не правильно.
1. Если убрать совсем, то можно навставлять сколько угодно записей для одного пользователя
2. Если нет индекса, то для поиска текущей темы нужно будет проверить всю таблицу

Что нужно сделать:
1. Добавить уникальный индекс на колонку userId - это решит сразу и проблему поиска и проблему вставки дубликатов
2. В методе setTheme нужно использовать не update (иначе на пустой таблице все сломается), а upsert - он пытается создать запись, а если это не удается (по причине нарушения уникальности) - обновляет поля существующей записи

2023-07-31 19:30 UTC, Olegas approved these changes
Работ принята

2023-08-01 15:05 UTC, merged