WOM-14
iDenisOff/womba pull request #5
Opened 2023-06-04 17:04 UTC by sibstark

1. Добавлена верстка страницы Логина
2. Добавлен класс для работы с API
3. Добавлен AuthController с логикой авторизации, регистрации и логаута (на будущее)
4.

2023-06-04 19:13 UTC, ManukMamyan requested changes

2023-06-04 19:13 UTC, ManukMamyan commented on packages/client/src/utils/http.ts
> +  let q = ''
лучше не использовать однобуквенные переменные

2023-06-04 19:13 UTC, ManukMamyan commented on packages/client/src/utils/http.ts
> +  if (response?.status && response.status >= 200 && response.status < 300) {
просто return response?.status && response.status >= 200 && response.status < 300

2023-06-04 19:13 UTC, ManukMamyan commented on packages/client/src/utils/http.ts
> +      path: this.endpoint + url,
предлагаю сортировать - короткую запись в начало

2023-06-04 19:13 UTC, ManukMamyan commented on packages/client/src/ui/components/card/card.tsx
> +  const classes = classnames(className, 'card')
переменная больше нигде не используется

лучше просто className={classnames(className, 'card')}

2023-06-05 16:11 UTC, ManukMamyan approved these changes

2023-06-06 08:26 UTC, practicum-maxim-zyryanov approved these changes
_Перед мерджем прошу проверить корректность веток, т.к. `sibstark:main` в `isDenisOff:main` выглядит подозрительно._ 

По коду замечаний критичных нет, больше возникают просто вопросы к реализации, поэтому Approve

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/api/auth-api.ts
> +  read = undefined
Мне нравится задумка реализовать для API базовый класс `BaseAPI`, но очень странно видеть объявление абстрактного класса, результатом которого становится необходимость ставить абстрактным методам `undefined`. Использование `BaseAPI` позволяет нам заранее договориться об интерфейсе, а здесь получается мы не можем полагаться на договор, т.к. методы могут стать `undefined`. Зачем добавлять эти методы без реализации?

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/containers/login/index.tsx
> +  console.log(values)
Возможно оставлено на будущее, но `setError` пока не используется, поэтому может код и просто забыли дописать?

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/containers/login/index.tsx
> +          required: 'Обязательно',
Встречается дважды, а скорее всего и на других формах встретится, чем не повод для заведения константы?

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/controllers/auth-controller.ts
> +    }
Сейчас будет выведено `signed up` даже если произошла ошибка. Перепишем так:
```
 try {
   await this.api.signup(data)
   console.log('signed up')
} catch (e) {
    console.log('signup', e)
}
```

И сразу заметим схожесть в коде обработки ошибки с методом `logout`. Кроме того, `signin` содержит такую же проблему, и его тоже можно переписать. Если принять во внимание тот факт, что ошибка регистрации тоже интересна пользователю, то код обработки ошибок всех трех методов можно свести к одному. Чисто для иллюстрации приведу грубую реализацию:

```
withErrorHandling(func: string, data: any, msgDone: string) {
  try {
      await this.api[func](data)
      alert(msgDone)
      console.log(func + ' done')
  } catch (e: any) {
      alert(`Ошибка: ${e.reason}`)
      console.log(func, e)
} 

withErrorHandling('signin', data, 'Вы залогинены')
```

На самом деле весь этот код обработки ошибок можно запрятать в базовом классе и не писать много лишнего текста. Да и вместо названия функции скорее передавал бы стрелочную функцию с нужным телом.

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/controllers/auth-controller.ts
> +      alert(`Ошбка логина ${e.reason}`)
Опечатка

2023-06-06 08:26 UTC, practicum-maxim-zyryanov commented on packages/client/src/utils/http.ts
> +}
А вот ведь есть выделенное место под обработку ошибок, почему бы не организовать глобальную обработку по всем запросам здесь?

2023-06-06 08:28 UTC, sibstark commented on packages/client/src/containers/login/index.tsx
> +          required: 'Обязательно',
Да, можно завести константу.

2023-06-06 08:35 UTC, sibstark commented on packages/client/src/utils/http.ts
> +}
Это место для обработки именно ошибок не совсем подходит по причине
S из SOLID - именно эта функция ```errorProcessing``` отвечает за бросок ошибки, возможно форматирование ошибки, если ошибку не выбросить то API класс не поймет что ошибка произошла, такова логика этой функции.

Что делать с ошибкой - выводить в UI или проглотить, вывести в консоль не задача этой функции, решать что делать с ошибкой будет контроллер

2023-06-06 08:38 UTC, sibstark commented on packages/client/src/controllers/auth-controller.ts
> +    }
Я знаю о таком подходе, но он мне не очень нравится, мне нравится везде писать try/catch/finally, тем более у нас еще нет ```storage``` и редиректов на страницу после авторизации.

2023-06-06 08:39 UTC, sibstark commented on packages/client/src/containers/login/index.tsx
> +  console.log(values)
Да, это будет использоваться в будущем для того чтобы устанавливать ошибку в форму

2023-06-06 08:43 UTC, sibstark commented
> _Перед мерджем прошу проверить корректность веток, т.к. `sibstark:main` в `isDenisOff:main` выглядит подозрительно._
> 
> По коду замечаний критичных нет, больше возникают просто вопросы к реализации, поэтому Approve

<img width="590" alt="image" src="https://github.com/iDenisOff/womba/assets/15224416/160d82df-4289-44b4-a518-d0be1e66eef9">

С ветками все нормально, мы льем все в main ветку

2023-06-06 08:49 UTC, sibstark commented on packages/client/src/api/auth-api.ts
> +  read = undefined
Убрал эти методы.

2023-06-06 09:03 UTC, sibstark commented
Спасибо за ревью!

2023-06-06 11:27 UTC, merged